//! End-to-end tests for the memvault HTTP surface the openclaw MCP uses.
//!
//! These boot a **real** axum server over TCP, backed by an enrolled-agent
//! `LocalClient`, and drive it through `HttpApiClient` — the exact transport
//! the `mcp-memvault` plugin runs with (`MEMVAULT_URL=http://127.0.0.1:8401`).
//! Each MCP tool is a thin wrapper over a `MemvaultClient` call (or a
//! `memvault_api::vfs::*` helper that composes several), so exercising those
//! here covers the tool surface faithfully — and would have caught the stubbed
//! `add_link`/`edges_of`/`add_entity` paths that made `vfs_mkdir` return
//! entity:000…000 with no resolvable path.

use std::collections::{HashMap, HashSet};
use std::sync::Arc;

use ed25519_dalek::{Signer, SigningKey};
use tokio::sync::{OnceCell, RwLock};

use memvault_api::agent_identity::{AgentIdentity, enroll_local_agent};
use memvault_api::{EventBus, HttpApiClient, LocalClient, MemvaultClient};
use memvault_auth::node_attestation::{AttestationOrigin, NodeAttestation};
use memvault_auth::{AgentRole, jwt::NodeTrust};
use memvault_core::{AgentName, BucketId, ClusterId, NodeRef, PeerId, Visibility};
use memvault_doc::Entity;
use memvault_query::QuotaManager;
use memvault_store::MemvaultStore;
use memvault_web::{AppState, build_router};

const AGENT_ID: &str = "test-agent";

struct TestServer {
    base_url: String,
    identity: Arc<AgentIdentity>,
    /// The bus `/api/v1/events` streams from.
    event_bus: Arc<EventBus>,
}

static SERVER: OnceCell<TestServer> = OnceCell::const_new();

/// Boot the enrolled-agent server once for the whole test binary.
async fn server() -> &'static TestServer {
    SERVER
        .get_or_init(|| async {
            // reqwest (used by HttpApiClient) is built with rustls-no-provider;
            // install a process-wide crypto provider before any client is built.
            let _ = rustls::crypto::ring::default_provider().install_default();

            // Deterministic admin + node keys; the agent key is generated by
            // `enroll_local_agent` and lives in `identity_dir`.
            let admin = SigningKey::from_bytes(&[0xA7u8; 32]);
            let node = SigningKey::from_bytes(&[0xB7u8; 32]);
            let cluster_id = ClusterId([0x11u8; 32]);

            let dir = std::env::temp_dir().join(format!("mv-mcp-e2e-{}", std::process::id()));
            let _ = std::fs::remove_dir_all(&dir);
            std::fs::create_dir_all(&dir).unwrap();
            // ACL helpers (enforce_*/filter_readable) lazily open the global
            // client from MEMVAULT_DB unless one is injected; point it at this
            // temp store so nothing touches a real ~/.local/share db.
            unsafe {
                std::env::set_var("MEMVAULT_DATA_DIR", &dir);
                std::env::set_var("MEMVAULT_DB", dir.join("blocks.redb"));
            }

            let store = Arc::new(MemvaultStore::open(dir.join("blocks.redb")).unwrap());
            let client = Arc::new(LocalClient::new(
                store,
                Arc::new(RwLock::new(QuotaManager::new(Default::default()))),
                Arc::new(EventBus::new(64)),
                node.verifying_key().to_bytes().to_vec(),
                cluster_id.0.to_vec(),
            ));

            // Minimal genesis so the agent can be enrolled and ACL resolves.
            let genesis = memvault_auth::sign_admin_genesis(&admin, cluster_id.clone(), 1)
                .expect("sign_admin_genesis");
            client.set_admin_signing_key(admin.clone());
            client.set_pinned_admin_genesis(genesis);
            client.set_node_signing_key(node.clone());

            let identity = enroll_local_agent(
                &client,
                AGENT_ID,
                &dir.join("agent"),
                AgentRole::AgentHost,
                u64::MAX,
            )
            .expect("enroll_local_agent");
            let agent_pubkey = identity.verifying_key.to_bytes();

            // The ACL helpers consult the process-global client.
            memvault_web::ui::state::set_client(Arc::clone(&client));

            // Auth fixtures: admin-signed node attestation (node_trust) and an
            // agent-attestation lookup matching the enrolled agent.
            let mut node_att = NodeAttestation {
                cluster_id: cluster_id.clone(),
                member: PeerId(node.verifying_key().as_bytes().to_vec()),
                not_after_ns: u64::MAX,
                issued_via: AttestationOrigin::Direct,
                signature: [0u8; 64],
            };
            node_att.signature = admin.sign(&node_att.signing_bytes().unwrap()).to_bytes();
            let mut trust = HashMap::new();
            trust.insert(
                node.verifying_key().to_bytes(),
                NodeTrust::Attested(node_att),
            );

            let agent_att = memvault_auth::sign_agent_attestation(
                &node,
                AgentName(AGENT_ID.to_string()),
                agent_pubkey,
                AgentRole::AgentHost,
                u64::MAX,
            )
            .expect("sign_agent_attestation");
            let lookup_att = agent_att.clone();

            let event_bus = Arc::new(EventBus::new(64));
            let state = Arc::new(AppState {
                client: Arc::clone(&client) as Arc<dyn MemvaultClient>,
                event_bus: Arc::clone(&event_bus),
                admin_pubkey: Some(admin.verifying_key()),
                node_trust: Arc::new(std::sync::RwLock::new(trust)),
                revoked_agents: Arc::new(std::sync::RwLock::new(HashSet::new())),
                revoked_nodes: Arc::new(std::sync::RwLock::new(HashSet::new())),
                metrics: Arc::new(memvault_api::metrics::Metrics::new()),
                agent_attestation_lookup: Some(Arc::new(move |pk: &[u8; 32]| {
                    (*pk == lookup_att.agent_pubkey).then(|| lookup_att.clone())
                })),
                allowed_origins: vec![],
            });

            let router = build_router(state);

            // Run the server on its OWN thread + runtime. `#[tokio::test]`
            // gives each test a fresh runtime that is torn down when the test
            // ends; a server spawned on the first test's runtime would die and
            // every later test would see "error sending request". A dedicated
            // thread keeps it alive for the whole test binary.
            let (tx, rx) = std::sync::mpsc::channel();
            std::thread::spawn(move || {
                let rt = tokio::runtime::Builder::new_current_thread()
                    .enable_all()
                    .build()
                    .unwrap();
                rt.block_on(async move {
                    let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
                    tx.send(listener.local_addr().unwrap()).unwrap();
                    let _ = axum::serve(listener, router).await;
                });
            });
            let addr = rx.recv().unwrap();

            TestServer {
                base_url: format!("http://{addr}"),
                identity: Arc::new(identity),
                event_bus,
            }
        })
        .await
}

/// An authenticated HTTP client + the enrolled agent's own bucket.
async fn client_and_bucket() -> (HttpApiClient, BucketId) {
    let s = server().await;
    let client = HttpApiClient::new(&s.base_url, Some(Arc::clone(&s.identity))).unwrap();
    // The server derives the bucket from the JWT pubkey; the bytes here are
    // ignored over HTTP. Pass the real identity pubkey anyway.
    let bucket = client
        .ensure_agent_bucket(&s.identity.verifying_key.to_bytes(), AGENT_ID)
        .await
        .expect("ensure_agent_bucket");
    (client, bucket)
}

/// A dedicated bucket so VFS tests don't race on a shared root.
async fn fresh_bucket(client: &HttpApiClient, name: &str) -> BucketId {
    client
        .bucket_create(
            name,
            None,
            Visibility::Internal,
            memvault_core::classification::Classification::Internal,
            memvault_core::BucketRole::Standard,
        )
        .await
        .expect("bucket_create")
}

const ZERO: [u8; 32] = [0u8; 32];

#[tokio::test]
async fn vfs_mkdir_resolve_ls_tree_round_trip() {
    let (client, _agent_bucket) = client_and_bucket().await;
    let bucket = fresh_bucket(&client, "vfs-mkdir-test").await;

    // mkdir -p /reports/2026 — the regression: this used to return
    // entity:000…000 and leave nothing resolvable.
    let id = client
        .vfs_mkdir(&bucket, "/reports/2026")
        .await
        .expect("mkdir");
    assert_ne!(id.0, ZERO, "mkdir must return a real (non-zero) entity id");

    // The leaf resolves.
    let resolved = client
        .vfs_resolve(&bucket, "/reports/2026")
        .await
        .expect("resolve_path");
    assert!(resolved.is_some(), "freshly created dir must resolve");

    // ls / shows reports.
    let entries = client.vfs_ls(&bucket, "/", false).await.expect("ls");
    assert!(
        entries.iter().any(|e| e.name == "reports"),
        "ls / must list the new 'reports' dir, got {:?}",
        entries.iter().map(|e| &e.name).collect::<Vec<_>>()
    );

    // tree contains the nested path.
    let tree = client.vfs_tree(&bucket, "/", 10).await.expect("tree");
    assert!(
        tree.contains("2026"),
        "tree must include the nested dir: {tree}"
    );

    // A path that doesn't exist is "not found" (404), not a server error.
    for err in [
        client
            .vfs_ls(&bucket, "/nowhere", true)
            .await
            .expect_err("ls of a missing path")
            .to_string(),
        client
            .vfs_tree(&bucket, "/nowhere", 3)
            .await
            .expect_err("tree of a missing path")
            .to_string(),
    ] {
        assert!(
            err.contains("404") || err.to_lowercase().contains("not found"),
            "{err}"
        );
        assert!(!err.contains("500"), "{err}");
    }
}

#[tokio::test]
async fn graph_entity_and_edges_round_trip() {
    let (client, bucket) = client_and_bucket().await;

    let mut props = std::collections::BTreeMap::new();
    props.insert("name".to_string(), serde_json::json!("alice"));
    let parent = client
        .add_entity(
            Entity {
                id: memvault_core::EntityId::random(),
                kind: "person".to_string(),
                props: props.clone(),
                edges_out: vec![],
            },
            Visibility::Internal,
            Some(&bucket),
        )
        .await
        .expect("add_entity parent");
    assert_ne!(parent.0, ZERO, "add_entity must not return a zero id");

    // get_entity round-trips.
    let got = client.get_entity(&parent).await.expect("get_entity");
    assert_eq!(got.expect("entity present").kind, "person");

    let child = client
        .add_entity(
            Entity {
                id: memvault_core::EntityId::random(),
                kind: "person".to_string(),
                props,
                edges_out: vec![],
            },
            Visibility::Internal,
            Some(&bucket),
        )
        .await
        .expect("add_entity child");

    let parent_ref = NodeRef::Entity(parent);
    let child_ref = NodeRef::Entity(child);

    // add_link used to be a no-op returning a random id; now it persists.
    let edge = memvault_doc::Edge {
        id: memvault_core::EdgeId::random(),
        relation: "knows".to_string(),
        target: child_ref.clone(),
        weight: None,
        props: Default::default(),
        provenance: None,
    };
    client
        .add_link(&parent_ref, edge, Visibility::Internal)
        .await
        .expect("add_link");

    // edges_of used to discard the response; now it returns the edge.
    let edges = client.edges_of(&parent_ref).await.expect("edges_of");
    assert!(
        edges
            .iter()
            .any(|(src, e)| *src == parent_ref && e.relation == "knows" && e.target == child_ref),
        "edges_of must return the persisted 'knows' edge"
    );
}

#[tokio::test]
async fn buckets_list_and_get_decode() {
    let (client, bucket) = client_and_bucket().await;

    // bucket_list/get used to fail to decode (server omitted required fields
    // and emitted hex ids that BucketId can't deserialize).
    let list = client.bucket_list().await.expect("bucket_list");
    assert!(
        list.iter().any(|b| b.id == bucket),
        "bucket_list must contain the agent bucket"
    );

    let got = client.bucket_get(&bucket).await.expect("bucket_get");
    let got = got.expect("agent bucket present");
    assert_eq!(got.id, bucket);
    // The elaborate fields are present (role defaults to Agent for agent buckets).
    assert_eq!(got.role, memvault_core::BucketRole::Agent);
}

#[tokio::test]
async fn docs_put_get_and_search() {
    let (client, bucket) = client_and_bucket().await;

    let mut fm = std::collections::BTreeMap::new();
    fm.insert("title".to_string(), serde_json::json!("Quarterly Report"));
    let doc = memvault_doc::Document {
        id: memvault_core::DocId([0u8; 32]), // ignored; server assigns the id
        frontmatter: fm,
        body: "the kangaroo metric improved this quarter".to_string(),
    };
    let cid = client
        .put_doc(doc.clone(), vec![], Visibility::Internal, Some(&bucket))
        .await
        .expect("put_doc");
    assert!(!cid.is_empty(), "put_doc returns a cid");

    // search used to discard the response; the hit carries the authoritative
    // DocId (distinct from the 36-byte block CID returned by put_doc).
    let hits = client.search("kangaroo", 10).await.expect("search");
    let doc_id = hits
        .first()
        .expect("search must find the indexed doc")
        .doc_id
        .clone();

    let got = client.get_doc(&doc_id).await.expect("get_doc");
    assert_eq!(
        got.expect("doc present").body,
        "the kangaroo metric improved this quarter"
    );

    // list_docs used to drop every row (server sent `doc:<hex>` labels, client
    // hand-parsed them as bare hex). It now decodes DocSummary directly.
    let docs = client
        .list_docs(None, 50, Some(&bucket))
        .await
        .expect("list_docs");
    assert!(
        docs.iter().any(|d| d.id == doc_id),
        "list_docs must return the doc it stored, got {} rows",
        docs.len()
    );
    // The summary's cid is the content address, round-trips as CID bytes.
    let summary = docs.iter().find(|d| d.id == doc_id).unwrap();
    assert!(!summary.cid.is_empty(), "DocSummary.cid must be populated");
}

#[tokio::test]
async fn views_crud_round_trip() {
    let (client, _bucket) = client_and_bucket().await;

    let view = memvault_api::View {
        name: "e2e-view".to_string(),
        tags: vec![("kind".to_string(), "note".to_string())],
        created_ns: 0,
        cid: String::new(),
        bucket_id: None,
    };
    client.create_view(view.clone()).await.expect("create_view");

    let views = client.list_views().await.expect("list_views");
    assert!(
        views.iter().any(|v| v.name == "e2e-view"),
        "view must be listed"
    );

    let got = client.get_view("e2e-view").await.expect("get_view");
    assert!(got.is_some(), "get_view must return the created view");

    client.delete_view("e2e-view").await.expect("delete_view");
    let after = client.list_views().await.expect("list_views after delete");
    assert!(
        !after.iter().any(|v| v.name == "e2e-view"),
        "view must be gone after delete"
    );
}

#[tokio::test]
async fn vfs_link_unlink_round_trip() {
    let (client, _agent_bucket) = client_and_bucket().await;
    let bucket = fresh_bucket(&client, "vfs-link-test").await;

    // Create an entity (its 32-byte id is known exactly), link it at a VFS
    // path, confirm it resolves, then unlink.
    let entity = client
        .add_entity(
            Entity {
                id: memvault_core::EntityId::random(),
                kind: "note".to_string(),
                props: Default::default(),
                edges_out: vec![],
            },
            Visibility::Internal,
            Some(&bucket),
        )
        .await
        .expect("add_entity");
    let node_id = format!("entity:{}", hex::encode(entity.0));

    let target = memvault_core::NodeRef::from_tag_label(&node_id).expect("node ref");
    client
        .vfs_link(&bucket, "/notes/linked.md", &target)
        .await
        .expect("vfs_link");

    let resolved = client
        .vfs_resolve(&bucket, "/notes/linked.md")
        .await
        .expect("resolve_path");
    assert!(resolved.is_some(), "linked node must resolve at its path");

    client
        .vfs_unlink(&bucket, "/notes/linked.md")
        .await
        .expect("unlink_path");
    let after = client
        .vfs_resolve(&bucket, "/notes/linked.md")
        .await
        .expect("resolve_path after unlink");
    assert!(after.is_none(), "node must be gone after unlink");
}

#[tokio::test]
async fn tags_add_and_get() {
    let (client, bucket) = client_and_bucket().await;
    let entity = client
        .add_entity(
            Entity {
                id: memvault_core::EntityId::random(),
                kind: "thing".to_string(),
                props: Default::default(),
                edges_out: vec![],
            },
            Visibility::Internal,
            Some(&bucket),
        )
        .await
        .expect("add_entity");
    let node_id = format!("entity:{}", hex::encode(entity.0));

    client
        .add_tags(&node_id, vec![("color".to_string(), "blue".to_string())])
        .await
        .expect("add_tags");
    let tags = client.get_tags(&node_id).await.expect("get_tags");
    assert!(
        tags.iter().any(|(s, l)| s == "color" && l == "blue"),
        "get_tags must return the added tag"
    );
}

#[tokio::test]
async fn status_reports_node() {
    let (client, _bucket) = client_and_bucket().await;
    // status() backs the memvault_status MCP tool.
    let status = client.status().await.expect("status");
    // NodeStatus now decodes peer_id/cluster_id (the old hand-parse dropped
    // them — it returned empty vecs).
    assert!(!status.peer_id.is_empty(), "status must carry peer_id");
    assert!(
        !status.cluster_id.is_empty(),
        "status must carry cluster_id"
    );
}

#[tokio::test]
async fn listing_and_vfs_are_bucket_scoped() {
    let (client, _agent) = client_and_bucket().await;
    let a = fresh_bucket(&client, "scope-a").await;
    let b = fresh_bucket(&client, "scope-b").await;

    // A doc in each bucket.
    let mk = |body: &str| memvault_doc::Document {
        id: memvault_core::DocId([0u8; 32]),
        frontmatter: Default::default(),
        body: body.to_string(),
    };
    client
        .put_doc(mk("alpha doc"), vec![], Visibility::Internal, Some(&a))
        .await
        .expect("put a");
    client
        .put_doc(mk("beta doc"), vec![], Visibility::Internal, Some(&b))
        .await
        .expect("put b");

    // list_docs must be bucket-scoped: the two buckets return disjoint,
    // non-empty doc sets. (The old HTTP client dropped the bucket param, so
    // every bucket returned the same all-buckets list.)
    let da = client.list_docs(None, 50, Some(&a)).await.expect("list a");
    let db = client.list_docs(None, 50, Some(&b)).await.expect("list b");
    let aids: std::collections::HashSet<_> = da.iter().map(|d| d.id.clone()).collect();
    let bids: std::collections::HashSet<_> = db.iter().map(|d| d.id.clone()).collect();
    assert!(
        !aids.is_empty() && !bids.is_empty(),
        "each bucket must list its own doc"
    );
    assert!(
        aids.is_disjoint(&bids),
        "list_docs must be bucket-scoped, not global"
    );

    // VFS in the non-default bucket B: mkdir → resolve → tree (the
    // customer-plan-ai symptom was resolve failing / tree empty here).
    client.vfs_mkdir(&b, "/scoped/dir").await.expect("mkdir b");
    assert!(
        client
            .vfs_resolve(&b, "/scoped/dir")
            .await
            .expect("resolve b")
            .is_some(),
        "VFS path must resolve in a non-default bucket"
    );
    let tree = client.vfs_tree(&b, "/", 10).await.expect("tree b");
    assert!(
        tree.contains("scoped"),
        "tree must show the dir in bucket B: {tree}"
    );
    // list_entities is bucket-scoped: B's root entity must be visible.
    let ents_b = client
        .list_entities(50, Some(&b))
        .await
        .expect("list_entities b");
    assert!(!ents_b.is_empty(), "bucket B must surface its VFS entities");
}

#[tokio::test]
async fn traverse_from_returns_neighbours() {
    let (client, bucket) = client_and_bucket().await;
    let a = client
        .add_entity(
            Entity {
                id: memvault_core::EntityId::random(),
                kind: "n".to_string(),
                props: Default::default(),
                edges_out: vec![],
            },
            Visibility::Internal,
            Some(&bucket),
        )
        .await
        .expect("add a");
    let b = client
        .add_entity(
            Entity {
                id: memvault_core::EntityId::random(),
                kind: "n".to_string(),
                props: Default::default(),
                edges_out: vec![],
            },
            Visibility::Internal,
            Some(&bucket),
        )
        .await
        .expect("add b");
    let a_ref = NodeRef::Entity(a);
    let b_ref = NodeRef::Entity(b);
    client
        .add_link(
            &a_ref,
            memvault_doc::Edge {
                id: memvault_core::EdgeId::random(),
                relation: "rel".to_string(),
                target: b_ref.clone(),
                weight: None,
                props: Default::default(),
                provenance: None,
            },
            Visibility::Internal,
        )
        .await
        .expect("add_link");

    // traverse_from used to return empty (no /traverse route + client stub).
    let hits = client
        .traverse_from(&a_ref, None, 2)
        .await
        .expect("traverse_from");
    assert!(
        hits.iter().any(|h| h.node == b_ref),
        "traverse from A must reach B"
    );
}

#[tokio::test]
async fn pin_unpin_and_extracted_text() {
    let (client, bucket) = client_and_bucket().await;
    // Upload a small text file, then exercise pin/unpin/extracted-text — these
    // used to be no-op/empty stubs with no server routes at all.
    let cid = client
        .upload_file(
            b"hello pinned world",
            Some("note.txt"),
            "text/plain",
            vec![],
            "internal",
            Some(&bucket),
        )
        .await
        .expect("upload_file");
    client.pin_file(&cid).await.expect("pin_file");
    // list_pinned must succeed over HTTP (it used to be an empty stub). The
    // exact pin bookkeeping (manifest vs content cid) is LocalClient-internal,
    // so we only require the round-trip to work, not a specific membership.
    let _pinned = client.list_pinned().await.expect("list_pinned");
    client.unpin_file(&cid).await.expect("unpin_file");
    // extracted-text may be None for a plain upload; the call must succeed.
    client
        .read_extracted_text(&cid)
        .await
        .expect("read_extracted_text");
}

#[tokio::test]
async fn links_from_documents() {
    // A document can be a link's source like any node (it used to be a 500).
    let (client, bucket) = client_and_bucket().await;
    let mut fm = std::collections::BTreeMap::new();
    fm.insert("title".to_string(), serde_json::json!("Converted text"));
    let doc = memvault_doc::Document {
        id: memvault_core::DocId([0u8; 32]),
        frontmatter: fm,
        body: "the wombat measurements".to_string(),
    };
    client
        .put_doc(doc, vec![], Visibility::Internal, Some(&bucket))
        .await
        .expect("put_doc");
    let doc_id = client
        .search("wombat", 10)
        .await
        .expect("search")
        .first()
        .expect("the doc is indexed")
        .doc_id
        .clone();
    let doc_ref = NodeRef::Doc(doc_id);

    let cid = client
        .upload_file(
            b"original bytes",
            Some("orig.txt"),
            "text/plain",
            vec![],
            "internal",
            Some(&bucket),
        )
        .await
        .expect("upload_file");
    let file_ref =
        NodeRef::from_tag_label(&format!("file:{}", hex::encode(&cid))).expect("a file node");
    let entity = client
        .add_entity(
            Entity {
                id: memvault_core::EntityId::random(),
                kind: "note".into(),
                props: Default::default(),
                edges_out: vec![],
            },
            Visibility::Internal,
            Some(&bucket),
        )
        .await
        .expect("add_entity");

    for (target, relation) in [
        (file_ref.clone(), "original"),
        (NodeRef::Entity(entity), "about"),
    ] {
        let edge = memvault_doc::Edge {
            id: memvault_core::EdgeId::random(),
            relation: relation.into(),
            target: target.clone(),
            weight: None,
            props: Default::default(),
            provenance: None,
        };
        client
            .add_link(&doc_ref, edge, Visibility::Internal)
            .await
            .unwrap_or_else(|e| panic!("doc -> {relation}: {e}"));
    }
    let edges = client.edges_of(&doc_ref).await.expect("edges_of");
    assert!(
        edges
            .iter()
            .any(|(s, e)| *s == doc_ref && e.target == file_ref && e.relation == "original"),
        "{edges:?}"
    );
}

#[tokio::test]
async fn created_docs_keep_the_clients_id() {
    // The id create_doc hands out (what memvault-mcp's put returns) must be
    // the stored one over HTTP too; it used to be a random id the server
    // never saw, so links from it failed.
    let (client, bucket) = client_and_bucket().await;
    let made = memvault_api::docs::create_doc(
        &client,
        "the quokka appendix",
        Some("Quokka"),
        None,
        vec![],
        Visibility::Internal,
        None,
        Some(&bucket),
    )
    .await
    .expect("create_doc");
    let got = client
        .get_doc(&made.doc_id)
        .await
        .expect("get_doc")
        .expect("the returned id is the stored one");
    assert!(got.body.contains("quokka"));
    let entity = client
        .add_entity(
            Entity {
                id: memvault_core::EntityId::random(),
                kind: "note".into(),
                props: Default::default(),
                edges_out: vec![],
            },
            Visibility::Internal,
            Some(&bucket),
        )
        .await
        .expect("add_entity");
    let edge = memvault_doc::Edge {
        id: memvault_core::EdgeId::random(),
        relation: "about".into(),
        target: NodeRef::Entity(entity),
        weight: None,
        props: Default::default(),
        provenance: None,
    };
    client
        .add_link(
            &NodeRef::Doc(made.doc_id.clone()),
            edge,
            Visibility::Internal,
        )
        .await
        .expect("a link from the new doc");
    // A client can't take an existing document's id.
    let again = memvault_doc::Document {
        id: made.doc_id.clone(),
        frontmatter: Default::default(),
        body: "overwrite?".into(),
    };
    let err = client
        .put_doc(again, vec![], Visibility::Internal, Some(&bucket))
        .await
        .expect_err("taken id")
        .to_string();
    assert!(err.contains("409"), "{err}");
}

#[tokio::test]
async fn uploaded_files_land_at_their_vfs_path_over_http() {
    let (client, bucket) = client_and_bucket().await;
    let (_cid, node) = memvault_api::files::upload_file(
        &client,
        b"%PDF-1.4 tiny",
        Some("r.pdf"),
        "application/pdf",
        vec![],
        "internal",
        Some("/papers/r.pdf"),
        Some(&bucket),
    )
    .await
    .expect("upload_file");
    let resolved = client
        .vfs_resolve(&bucket, "/papers/r.pdf")
        .await
        .expect("resolve");
    assert_eq!(
        resolved.map(|(n, _)| n.tag_label()),
        Some(node),
        "the file is at its path"
    );
}

#[tokio::test]
async fn buckets_of_others_are_not_listed() {
    let (client, own) = client_and_bucket().await;
    // A bucket another agent owns, made directly on the daemon.
    let local = memvault_web::ui::state::local_client().unwrap();
    let theirs = local
        .bucket_create_as(
            AgentName("someone-else".into()),
            Some([9u8; 32]),
            "not-yours",
            None,
            Visibility::Internal,
            memvault_core::classification::Classification::Internal,
            memvault_core::BucketRole::Standard,
        )
        .await
        .unwrap();
    let ids: Vec<BucketId> = client
        .bucket_list()
        .await
        .unwrap()
        .into_iter()
        .map(|b| b.id)
        .collect();
    assert!(ids.contains(&own), "its own bucket is listed");
    assert!(!ids.contains(&theirs), "another agent's bucket isn't");
    assert!(
        client
            .bucket_get(&theirs)
            .await
            .map(|b| b.is_none())
            .unwrap_or(true),
        "nor can it be opened"
    );
}

#[tokio::test]
async fn labels_come_from_the_index() {
    let (client, bucket) = client_and_bucket().await;
    let mut fm = std::collections::BTreeMap::new();
    fm.insert("title".to_string(), serde_json::json!("A long book"));
    let doc = memvault_doc::Document {
        id: memvault_core::DocId([0u8; 32]),
        frontmatter: fm,
        body: "word ".repeat(100_000),
    };
    client
        .put_doc(
            doc,
            vec![("kind".into(), "book".into())],
            Visibility::Internal,
            Some(&bucket),
        )
        .await
        .unwrap();
    // Listed from the envelope's head (the 100k-word body isn't decoded).
    let docs = client.list_docs(None, 50, Some(&bucket)).await.unwrap();
    let d = docs
        .iter()
        .find(|d| d.title.as_deref() == Some("A long book"))
        .expect("listed");
    assert!(
        d.tags.contains(&("kind".to_string(), "book".to_string())),
        "with its tags: {:?}",
        d.tags
    );
    let label = client
        .resolve_label(&format!("doc:{}", hex::encode(d.id.0)))
        .await
        .unwrap();
    assert_eq!(label.as_deref(), Some("A long book"));
    assert_eq!(
        client.resolve_label("doc:00").await.unwrap(),
        None,
        "unknown: none"
    );
}

#[tokio::test]
async fn audit_names_files_and_hides_other_buckets() {
    let (client, bucket) = client_and_bucket().await;
    let mine = client
        .upload_file(
            b"audit me",
            Some("mine.txt"),
            "text/plain",
            vec![],
            "internal",
            Some(&bucket),
        )
        .await
        .unwrap();
    let local = memvault_web::ui::state::local_client().unwrap();
    let theirs = local
        .bucket_create_as(
            AgentName("audit-other".into()),
            Some([7u8; 32]),
            "audit-other",
            None,
            Visibility::Internal,
            memvault_core::classification::Classification::Internal,
            memvault_core::BucketRole::Standard,
        )
        .await
        .unwrap();
    let other = local
        .upload_file(
            b"not yours",
            Some("theirs.txt"),
            "text/plain",
            vec![],
            "internal",
            Some(&theirs),
        )
        .await
        .unwrap();
    let q = memvault_query::AuditQuery {
        op_kind: Some(memvault_query::OpKind::AttachFile),
        limit: Some(5000),
        ..Default::default()
    };
    let files: Vec<Vec<u8>> = client
        .audit(q)
        .await
        .unwrap()
        .into_iter()
        .filter_map(|r| r.attachment_cid)
        .collect();
    assert!(
        files.contains(&mine),
        "an upload's record names its file (the UI's Files page lists from it)"
    );
    assert!(
        !files.contains(&other),
        "another agent's bucket stays out of the audit log"
    );
    // The UI's Files page names files from their manifests, over HTTP in jwt mode.
    let m = client
        .get_file_manifest(&mine)
        .await
        .unwrap()
        .expect("a manifest");
    let m = memvault_store::deserialize_block(&m).expect("readable");
    assert_eq!(m["filename"], "mine.txt");
    assert_eq!(m["content_size"], 8);
}

#[tokio::test]
async fn docs_of_others_are_not_listed() {
    let (client, bucket) = client_and_bucket().await;
    let local = memvault_web::ui::state::local_client().unwrap();
    let theirs = local
        .bucket_create_as(
            AgentName("docs-other".into()),
            Some([5u8; 32]),
            "docs-other",
            None,
            Visibility::Internal,
            memvault_core::classification::Classification::Internal,
            memvault_core::BucketRole::Standard,
        )
        .await
        .unwrap();
    let titled = |t: &str| {
        let mut fm = std::collections::BTreeMap::new();
        fm.insert("title".to_string(), serde_json::json!(t));
        memvault_doc::Document {
            id: memvault_core::DocId([0u8; 32]),
            frontmatter: fm,
            body: "text".into(),
        }
    };
    client
        .put_doc(
            titled("mine, listed"),
            vec![],
            Visibility::Internal,
            Some(&bucket),
        )
        .await
        .unwrap();
    local
        .put_doc(
            titled("theirs, hidden"),
            vec![],
            Visibility::Internal,
            Some(&theirs),
        )
        .await
        .unwrap();
    // No bucket named: the caller's agent bucket (standards/bucket-scoping.md).
    let titles: Vec<String> = client
        .list_docs(None, 500, None)
        .await
        .unwrap()
        .into_iter()
        .filter_map(|d| d.title)
        .collect();
    assert!(titles.iter().any(|t| t == "mine, listed"), "{titles:?}");
    assert!(
        !titles.iter().any(|t| t == "theirs, hidden"),
        "another agent's document isn't listed"
    );
}

/// The graph's listings leave out VFS directories (a reserved kind) *before*
/// the limit, over HTTP too: a bucket with more directories than `limit`
/// still lists its one real entity.
#[tokio::test]
async fn graph_listings_leave_out_reserved_kinds_before_the_limit() {
    let (client, _agent_bucket) = client_and_bucket().await;
    let bucket = fresh_bucket(&client, "reserved-kinds-test").await;
    client
        .vfs_mkdir(&bucket, "/a/b/c")
        .await
        .expect("mkdir creates several vfs:dir entities");
    let mut props = std::collections::BTreeMap::new();
    props.insert("name".to_string(), serde_json::json!("only-person"));
    let person = client
        .add_entity(
            Entity {
                id: memvault_core::EntityId::random(),
                kind: "person".to_string(),
                props,
                edges_out: vec![],
            },
            Visibility::Internal,
            Some(&bucket),
        )
        .await
        .expect("add_entity");

    let visible = client
        .list_visible_entities(1, Some(&bucket), false)
        .await
        .expect("list_visible_entities");
    assert_eq!(
        visible.iter().map(|e| e.id.clone()).collect::<Vec<_>>(),
        vec![person.clone()]
    );

    let rows = client
        .list_scoped(
            &memvault_core::QueryScope::all()
                .with_bucket(Some(bucket.clone()))
                .without_reserved(),
            100,
        )
        .await
        .expect("list_scoped");
    let person_id = format!("entity:{}", hex::encode(person.0));
    assert!(rows.iter().any(|r| r.node_id == person_id), "{rows:?}");
    assert!(
        rows.iter()
            .all(|r| r.node_type != "entity" || r.node_id == person_id),
        "only the person entity is listed, no vfs:dir: {rows:?}"
    );
}

// ── Access and bucket scoping over HTTP ──────────────────────────────

/// A bucket another agent owns, made directly on the daemon.
async fn others_bucket(name: &str, seed: u8) -> BucketId {
    let local = memvault_web::ui::state::local_client().unwrap();
    local
        .bucket_create_as(
            AgentName(name.into()),
            Some([seed; 32]),
            name,
            None,
            Visibility::Internal,
            memvault_core::classification::Classification::Internal,
            memvault_core::BucketRole::Standard,
        )
        .await
        .unwrap()
}

fn entity(kind: &str) -> Entity {
    Entity {
        id: memvault_core::EntityId::random(),
        kind: kind.to_string(),
        props: Default::default(),
        edges_out: vec![],
    }
}

fn titled(title: &str, body: &str) -> memvault_doc::Document {
    let mut fm = std::collections::BTreeMap::new();
    fm.insert("title".to_string(), serde_json::json!(title));
    memvault_doc::Document {
        id: memvault_core::DocId::random(),
        frontmatter: fm,
        body: body.into(),
    }
}

/// Store a titled document in `bucket`; its id.
async fn put(
    c: &dyn MemvaultClient,
    title: &str,
    body: &str,
    bucket: &BucketId,
) -> memvault_core::DocId {
    let d = titled(title, body);
    let id = d.id.clone();
    c.put_doc(d, vec![], Visibility::Internal, Some(bucket))
        .await
        .unwrap();
    id
}

fn edge(relation: &str, target: NodeRef) -> memvault_doc::Edge {
    memvault_doc::Edge {
        id: memvault_core::EdgeId::random(),
        relation: relation.to_string(),
        target,
        weight: None,
        props: Default::default(),
        provenance: None,
    }
}

fn skill(name: &str) -> memvault_api::SkillSpec {
    memvault_api::SkillSpec {
        name: name.to_string(),
        description: None,
        trigger: None,
        instruction_body: None,
    }
}

/// A raw request with the test agent's token, for status codes and routes
/// `HttpApiClient` doesn't expose.
async fn raw(method: reqwest::Method, path: &str) -> reqwest::RequestBuilder {
    let s = server().await;
    let token = s.identity.issue_jwt("read write admin", 3600).unwrap();
    reqwest::Client::new()
        .request(method, format!("{}/api/v1{path}", s.base_url))
        .bearer_auth(token)
}

#[tokio::test]
async fn writes_without_a_bucket_land_in_the_agent_bucket() {
    let (client, own) = client_and_bucket().await;
    let local = memvault_web::ui::state::local_client().unwrap();
    let file = client
        .upload_file(
            b"no bucket named",
            Some("nb.txt"),
            "text/plain",
            vec![],
            "internal",
            None,
        )
        .await
        .expect("an upload without a bucket goes to the agent bucket");
    assert_eq!(local.bucket_for_file(&file), Some(own.clone()));

    let e = client
        .add_entity(entity("note"), Visibility::Internal, None)
        .await
        .expect("an entity without a bucket goes to the agent bucket");
    assert_eq!(local.bucket_for_entity(&e), Some(own.clone()));

    let s = client
        .skill_publish(skill("no-bucket-skill"), Visibility::Internal, None)
        .await
        .expect("a skill without a bucket goes to the agent bucket");
    assert_eq!(local.bucket_for_entity(&s), Some(own.clone()));

    // An entity's vfs_path is honoured without a bucket too (it was dropped).
    let path = format!("/nb-entities/e-{}", std::process::id());
    let resp = raw(reqwest::Method::POST, "/entities")
        .await
        .json(&serde_json::json!({ "kind": "note", "vfs_path": path }))
        .send()
        .await
        .unwrap();
    assert_eq!(resp.status(), 201);
    let id = resp.json::<serde_json::Value>().await.unwrap()["node_id"]
        .as_str()
        .unwrap()
        .to_string();
    let at = client.vfs_resolve(&own, &path).await.unwrap();
    assert_eq!(at.map(|(n, _)| n.tag_label()), Some(id));
}

#[tokio::test]
async fn entity_and_skill_listings_default_to_the_agent_bucket() {
    let (client, own) = client_and_bucket().await;
    let elsewhere = fresh_bucket(&client, "listing-elsewhere").await;
    let home = client
        .add_entity(entity("home"), Visibility::Internal, Some(&own))
        .await
        .unwrap();
    let away = client
        .add_entity(entity("away"), Visibility::Internal, Some(&elsewhere))
        .await
        .unwrap();
    let ids: Vec<_> = client
        .list_entities(usize::MAX, None)
        .await
        .unwrap()
        .into_iter()
        .map(|e| e.id)
        .collect();
    assert!(ids.contains(&home), "the agent bucket's entity is listed");
    assert!(!ids.contains(&away), "another bucket's isn't, unless named");
    let named: Vec<_> = client
        .list_entities(usize::MAX, Some(&elsewhere))
        .await
        .unwrap()
        .into_iter()
        .map(|e| e.id)
        .collect();
    assert!(named.contains(&away));

    let home = client
        .skill_publish(skill("home-skill"), Visibility::Internal, Some(&own))
        .await
        .unwrap();
    let away = client
        .skill_publish(skill("away-skill"), Visibility::Internal, Some(&elsewhere))
        .await
        .unwrap();
    let ids: Vec<_> = client
        .skill_list(usize::MAX, None)
        .await
        .unwrap()
        .into_iter()
        .map(|s| s.id)
        .collect();
    assert!(ids.contains(&home), "the agent bucket's skill is listed");
    assert!(!ids.contains(&away), "another bucket's isn't, unless named");
}

#[tokio::test]
async fn traversal_and_links_skip_what_the_caller_cannot_read() {
    let (client, own) = client_and_bucket().await;
    let theirs = others_bucket("graph-other", 11).await;
    let local = memvault_web::ui::state::local_client().unwrap();
    let a = NodeRef::Entity(
        client
            .add_entity(entity("a"), Visibility::Internal, Some(&own))
            .await
            .unwrap(),
    );
    let c = NodeRef::Entity(
        client
            .add_entity(entity("c"), Visibility::Internal, Some(&own))
            .await
            .unwrap(),
    );
    let t = NodeRef::Entity(
        local
            .add_entity(entity("t"), Visibility::Internal, Some(&theirs))
            .await
            .unwrap(),
    );
    // a → t → c, and t → a (incoming to a from an unreadable node).
    local
        .add_link(&a, edge("to", t.clone()), Visibility::Internal)
        .await
        .unwrap();
    local
        .add_link(&t, edge("to", c.clone()), Visibility::Internal)
        .await
        .unwrap();
    local
        .add_link(&t, edge("back", a.clone()), Visibility::Internal)
        .await
        .unwrap();

    let reached: Vec<NodeRef> = client
        .traverse_from(&a, None, 3)
        .await
        .unwrap()
        .into_iter()
        .map(|h| h.node)
        .collect();
    assert!(!reached.contains(&t), "an unreadable node isn't returned");
    assert!(!reached.contains(&c), "nor walked through");

    let touching = client.edges_of(&a).await.unwrap();
    assert!(
        touching.iter().all(|(src, e)| *src != t && e.target != t),
        "edges to or from an unreadable node aren't listed: {touching:?}"
    );
}

#[tokio::test]
async fn pins_of_others_are_not_listed() {
    let (client, own) = client_and_bucket().await;
    let theirs = others_bucket("pins-other", 12).await;
    let local = memvault_web::ui::state::local_client().unwrap();
    let other = local
        .upload_file(
            b"their pin",
            Some("their-pin.txt"),
            "text/plain",
            vec![],
            "internal",
            Some(&theirs),
        )
        .await
        .unwrap();
    local.pin_file(&other).await.unwrap();
    let mine = client
        .upload_file(
            b"my pin",
            Some("my-pin.txt"),
            "text/plain",
            vec![],
            "internal",
            Some(&own),
        )
        .await
        .unwrap();
    client.pin_file(&mine).await.unwrap();
    let pinned: Vec<Vec<u8>> = client
        .list_pinned()
        .await
        .unwrap()
        .into_iter()
        .map(|(cid, _)| cid)
        .collect();
    assert!(!pinned.contains(&other), "{pinned:?}");
}

#[tokio::test]
async fn events_of_others_are_not_streamed() {
    let (client, own) = client_and_bucket().await;
    let theirs = others_bucket("events-other", 13).await;
    let local = memvault_web::ui::state::local_client().unwrap();
    let their_doc = put(&*local, "theirs", "x", &theirs).await;
    let my_doc = put(&client, "mine", "x", &own).await;
    let mut resp = raw(reqwest::Method::GET, "/events")
        .await
        .send()
        .await
        .unwrap();
    assert_eq!(resp.status(), 200);
    let bus = &server().await.event_bus;
    bus.publish(memvault_api::MemvaultEvent::DocCreated {
        doc_id: their_doc.clone(),
        cid: vec![1],
    });
    bus.publish(memvault_api::MemvaultEvent::DocCreated {
        doc_id: my_doc.clone(),
        cid: vec![2],
    });
    let mut seen = String::new();
    let mine = hex::encode(my_doc.0);
    while !seen.contains(&mine) {
        let chunk = tokio::time::timeout(std::time::Duration::from_secs(10), resp.chunk())
            .await
            .expect("the caller's own event arrives")
            .unwrap()
            .expect("stream open");
        seen.push_str(&String::from_utf8_lossy(&chunk));
    }
    assert!(
        !seen.contains(&hex::encode(their_doc.0)),
        "another agent's event isn't streamed: {seen}"
    );
}

#[tokio::test]
async fn buckets_of_others_cannot_be_inspected_or_changed() {
    let (client, _own) = client_and_bucket().await;
    let theirs = others_bucket("admin-other", 14).await;
    let canon = others_bucket("admin-other-canon", 15).await;
    let local = memvault_web::ui::state::local_client().unwrap();
    local.bucket_merge(&[theirs.clone()], &canon).await.unwrap();

    assert!(
        client.bucket_grants_list(&theirs).await.is_err(),
        "another agent's grants aren't listed"
    );
    let resp = raw(
        reqwest::Method::GET,
        &format!("/buckets/{}/grants", hex::encode(theirs.0)),
    )
    .await
    .send()
    .await
    .unwrap();
    assert_eq!(resp.status(), 404);
    let merges = client.bucket_merges().await.unwrap();
    assert!(
        !merges.iter().any(|(s, c)| *s == theirs || *c == canon),
        "another agent's merges aren't listed: {merges:?}"
    );

    assert!(client.bucket_rename(&theirs, "pwned").await.is_err());
    let name = local.bucket_get(&theirs).await.unwrap().unwrap().name;
    assert_ne!(name, "pwned", "another agent's bucket keeps its name");
    let resp = raw(
        reqwest::Method::POST,
        &format!("/buckets/{}/attach", hex::encode(theirs.0)),
    )
    .await
    .send()
    .await
    .unwrap();
    assert!(!resp.status().is_success(), "attach: {}", resp.status());

    // Its own buckets it may still rename.
    let mine = fresh_bucket(&client, "rename-me").await;
    client.bucket_rename(&mine, "renamed").await.unwrap();
}

#[tokio::test]
async fn limits_count_only_what_the_caller_may_read() {
    let (client, own) = client_and_bucket().await;
    let theirs = others_bucket("limit-other", 16).await;
    let local = memvault_web::ui::state::local_client().unwrap();
    let word = format!("qzlimit{}", std::process::id());
    let mine = put(&client, "mine", &word, &own).await;
    // Newer and more relevant documents the caller may not read.
    for i in 0..5 {
        put(
            &*local,
            &format!("theirs {i}"),
            &format!("{word} {word} {word} {word}"),
            &theirs,
        )
        .await;
        local
            .add_entity(entity("theirs"), Visibility::Internal, Some(&theirs))
            .await
            .unwrap();
    }
    let mut hits = vec![];
    for _ in 0..50 {
        hits = client.search(&word, 1).await.unwrap();
        if !hits.is_empty() {
            break;
        }
        tokio::time::sleep(std::time::Duration::from_millis(100)).await;
    }
    assert_eq!(
        hits.iter().map(|h| h.doc_id.clone()).collect::<Vec<_>>(),
        vec![mine],
        "a readable hit fills the limit"
    );
    assert_eq!(client.list_all(None, 1, None).await.unwrap().len(), 1);
    assert_eq!(client.list_entities(1, None).await.unwrap().len(), 1);
}

#[tokio::test]
async fn unreadable_documents_answer_404() {
    let (client, own) = client_and_bucket().await;
    let theirs = others_bucket("doc404-other", 17).await;
    let local = memvault_web::ui::state::local_client().unwrap();
    let doc = put(&*local, "hidden", "x", &theirs).await;
    let resp = raw(
        reqwest::Method::GET,
        &format!("/docs/{}", hex::encode(doc.0)),
    )
    .await
    .send()
    .await
    .unwrap();
    assert_eq!(resp.status(), 404);
    let body = resp.text().await.unwrap();
    assert!(!body.contains(&hex::encode(theirs.0)), "{body}");

    // A client-chosen id taken elsewhere is refused without saying so.
    let mine = put(&client, "taken", "x", &own).await;
    let mut messages = vec![];
    for id in [&doc, &mine] {
        let resp = raw(reqwest::Method::POST, "/docs")
            .await
            .json(&serde_json::json!({ "body": "x", "id": hex::encode(id.0) }))
            .send()
            .await
            .unwrap();
        assert_eq!(resp.status(), 409);
        messages.push(resp.text().await.unwrap());
    }
    assert_eq!(messages[0], messages[1], "the same answer either way");
    assert!(!messages[0].contains(&hex::encode(doc.0)));
}

#[tokio::test]
async fn links_to_unreadable_nodes_are_refused() {
    let (client, own) = client_and_bucket().await;
    let theirs = others_bucket("link-other", 18).await;
    let local = memvault_web::ui::state::local_client().unwrap();
    let doc = NodeRef::Doc(put(&*local, "hidden", "x", &theirs).await);
    assert!(
        client
            .vfs_link(&own, &format!("/stolen-{}", std::process::id()), &doc)
            .await
            .is_err(),
        "a VFS link to an unreadable node is refused"
    );
    let s = client
        .skill_publish(skill("linker"), Visibility::Internal, Some(&own))
        .await
        .unwrap();
    assert!(
        client
            .skill_link_resource(&s, &doc, "resource", None, false, Visibility::Internal)
            .await
            .is_err(),
        "a skill resource on an unreadable node is refused"
    );
}

#[tokio::test]
async fn malformed_bucket_params_are_rejected() {
    for path in [
        "/docs?bucket=zz",
        "/entities?bucket=zz",
        "/skills?bucket=zz",
        "/nodes?bucket=zz",
        "/search?q=x&bucket=zz",
    ] {
        let resp = raw(reqwest::Method::GET, path).await.send().await.unwrap();
        assert_eq!(resp.status(), 400, "GET {path}");
    }
    for path in ["/docs", "/entities", "/skills"] {
        let resp = raw(reqwest::Method::POST, path)
            .await
            .json(&serde_json::json!({ "body": "x", "kind": "k", "name": "n", "bucket": "zz" }))
            .send()
            .await
            .unwrap();
        assert_eq!(resp.status(), 400, "POST {path}");
    }
    let form = reqwest::multipart::Form::new().part(
        "file",
        reqwest::multipart::Part::bytes(b"x".to_vec()).file_name("x.txt"),
    );
    let resp = raw(reqwest::Method::POST, "/files?bucket=zz")
        .await
        .multipart(form)
        .send()
        .await
        .unwrap();
    assert_eq!(resp.status(), 400, "POST /files");
}

// ── Client parity: the methods the UI uses, over HTTP ────────────────

/// GET a JSON body with the test agent's token.
async fn get_json(path: &str) -> (reqwest::StatusCode, serde_json::Value) {
    let resp = raw(reqwest::Method::GET, path).await.send().await.unwrap();
    let status = resp.status();
    (status, resp.json().await.unwrap_or(serde_json::Value::Null))
}

/// No JSON array of numbers (a raw `[u8; N]`) anywhere in `v`.
fn assert_no_byte_arrays(v: &serde_json::Value, what: &str) {
    match v {
        serde_json::Value::Array(a) => {
            assert!(
                a.len() < 16 || !a.iter().all(|x| x.is_u64()),
                "{what}: a raw byte array on the wire: {v}"
            );
            a.iter().for_each(|x| assert_no_byte_arrays(x, what));
        }
        serde_json::Value::Object(o) => o.values().for_each(|x| assert_no_byte_arrays(x, what)),
        _ => {}
    }
}

#[tokio::test]
async fn edit_doc_over_http_applies_the_patch() {
    let (client, own) = client_and_bucket().await;
    let id = put(&client, "Editable", "hello world", &own).await;
    let cid = client
        .edit_doc(
            &id,
            memvault_doc::TextPatch {
                ops: vec![
                    memvault_doc::TextOp::Retain(5),
                    memvault_doc::TextOp::Insert(",".into()),
                    memvault_doc::TextOp::Retain(6),
                ],
            },
        )
        .await
        .expect("edit_doc over HTTP");
    assert!(!cid.is_empty(), "edit_doc returns the new envelope's cid");
    let got = client.get_doc(&id).await.unwrap().expect("doc");
    assert_eq!(got.body, "hello, world");
    let history = client.history_of(&id).await.unwrap();
    let kinds: Vec<_> = history.iter().map(|r| r.op_kind.clone()).collect();
    assert!(
        kinds.contains(&memvault_query::OpKind::DocEdit),
        "{kinds:?}"
    );
    assert!(history.iter().all(|r| r.doc_id.as_ref() == Some(&id)));
    assert!(
        history.iter().any(|r| r.cid == cid),
        "the edit's cid is listed"
    );
}

#[tokio::test]
async fn entity_history_over_http() {
    let (client, own) = client_and_bucket().await;
    let e = client
        .add_entity(entity("historic"), Visibility::Internal, Some(&own))
        .await
        .unwrap();
    let local = memvault_web::ui::state::local_client().unwrap();
    let want = local.entity_history(&e).await.unwrap();
    assert!(!want.is_empty());
    let got = client.entity_history(&e).await.unwrap();
    assert_eq!(
        got.iter()
            .map(|r| (r.cid.clone(), r.op_kind.clone()))
            .collect::<Vec<_>>(),
        want.iter()
            .map(|r| (r.cid.clone(), r.op_kind.clone()))
            .collect::<Vec<_>>(),
    );
}

#[tokio::test]
async fn uploads_keep_their_tags() {
    let (client, own) = client_and_bucket().await;
    let cid = client
        .upload_file(
            b"tagged upload",
            Some("tagged.txt"),
            "text/plain",
            vec![("topic".into(), "otters".into())],
            "internal",
            Some(&own),
        )
        .await
        .unwrap();
    let tags = client
        .get_tags(&format!("file:{}", hex::encode(&cid)))
        .await
        .unwrap();
    assert!(
        tags.contains(&("topic".to_string(), "otters".to_string())),
        "{tags:?}"
    );
}

#[tokio::test]
async fn retractions_return_their_record_and_keep_the_reason() {
    let (client, own) = client_and_bucket().await;
    let id = put(&client, "Retract me", "soon gone", &own).await;
    let rec = client
        .retract(&id.0, "a reason worth keeping")
        .await
        .expect("retract");
    assert!(!rec.is_empty(), "retract returns the retraction's cid");
    let local = memvault_web::ui::state::local_client().unwrap();
    let block = local.store().get_block(&rec).unwrap().expect("the record");
    let v = memvault_store::deserialize_block(&block).expect("readable");
    assert!(v.to_string().contains("a reason worth keeping"), "{v}");

    let e = client
        .add_entity(entity("short-lived"), Visibility::Internal, Some(&own))
        .await
        .unwrap();
    let label = format!("entity:{}", hex::encode(e.0));
    client
        .retract_node(&label, "node reason kept")
        .await
        .expect("retract_node");
    // The retraction is an annotation on the node.
    let found = local
        .store()
        .query_by_tag("_ann", &label, 0, usize::MAX)
        .unwrap()
        .iter()
        .filter_map(|c| local.store().get_block(c).ok().flatten())
        .filter_map(|b| memvault_store::deserialize_block(&b))
        .any(|v| v.to_string().contains("node reason kept"));
    assert!(found, "the node retraction keeps its reason");
}

#[tokio::test]
async fn tokens_issue_list_and_revoke_over_http() {
    let (client, _own) = client_and_bucket().await;
    let token = client
        .issue_token_ex(
            memvault_auth::TokenRole::Agent(AgentRole::Service),
            600,
            1,
            Some("e2e-token".into()),
            vec![],
        )
        .await
        .expect("issue_token over HTTP");
    assert!(!token.is_empty());
    let listed = client.list_tokens().await.expect("list_tokens");
    let t = listed
        .iter()
        .find(|t| t.label.as_deref() == Some("e2e-token"))
        .expect("the issued token is listed");
    client
        .revoke_token(&t.cid, "e2e revoke")
        .await
        .expect("revoke_token over HTTP");
    let after = client.list_tokens().await.unwrap();
    assert!(
        after.iter().any(|x| x.cid == t.cid && x.revoked),
        "revoked: {after:?}"
    );
}

#[tokio::test]
async fn bucket_lifecycle_over_http() {
    let (client, _own) = client_and_bucket().await;
    let a = fresh_bucket(&client, "life-a").await;
    let b = fresh_bucket(&client, "life-b").await;
    client.bucket_rename(&a, "life-a-renamed").await.unwrap();
    assert_eq!(
        client.bucket_get(&a).await.unwrap().unwrap().name,
        "life-a-renamed"
    );
    client.bucket_attach(&a).await.expect("attach");
    client
        .bucket_bind(&a, &ClusterId([0x11u8; 32]))
        .await
        .expect("bind over HTTP");
    client.bucket_merge(&[b.clone()], &a).await.expect("merge");
    assert!(
        client
            .bucket_merges()
            .await
            .unwrap()
            .contains(&(b.clone(), a.clone()))
    );
    client.bucket_unmerge(&b, &a).await.expect("unmerge");
    assert!(
        !client
            .bucket_merges()
            .await
            .unwrap()
            .contains(&(b.clone(), a.clone()))
    );
    client
        .bucket_archive(&b, "done with it")
        .await
        .expect("archive");
}

#[tokio::test]
async fn skills_crud_over_http() {
    let (client, own) = client_and_bucket().await;
    let s = client
        .skill_publish(
            memvault_api::SkillSpec {
                name: "crud-skill".into(),
                description: Some("d".into()),
                trigger: None,
                instruction_body: Some("do the thing".into()),
            },
            Visibility::Internal,
            Some(&own),
        )
        .await
        .unwrap();
    client.skill_rename(&s, "crud-skill-2").await.unwrap();
    let doc = NodeRef::Doc(put(&client, "resource", "r", &own).await);
    let edge = client
        .skill_link_resource(
            &s,
            &doc,
            memvault_core::SKILL_RESOURCE_REL,
            Some("r.md"),
            false,
            Visibility::Internal,
        )
        .await
        .unwrap();
    let bundle = client.skill_get(&s).await.unwrap().expect("bundle");
    assert_eq!(bundle.info.name, "crud-skill-2");
    assert!(bundle.resources.iter().any(|r| r.edge_id == edge));
    assert_eq!(bundle.instructions.len(), 1);
    client.skill_unlink_resource(&s, &edge).await.unwrap();
    client.skill_delete(&s, "bye").await.unwrap();
    assert!(
        !client
            .skill_list(usize::MAX, Some(&own))
            .await
            .unwrap()
            .iter()
            .any(|i| i.id == s && !i.retracted)
    );
}

#[tokio::test]
async fn update_view_over_http() {
    let (client, _own) = client_and_bucket().await;
    let name = format!("upd-view-{}", std::process::id());
    let mut view = memvault_api::View {
        name: name.clone(),
        tags: vec![("kind".into(), "a".into())],
        created_ns: 0,
        cid: String::new(),
        bucket_id: None,
    };
    client.create_view(view.clone()).await.unwrap();
    view.tags = vec![("kind".into(), "b".into())];
    client.update_view(view).await.unwrap();
    let got = client.get_view(&name).await.unwrap().expect("view");
    assert_eq!(got.tags, vec![("kind".to_string(), "b".to_string())]);
}

/// The scoped reads answer over HTTP what they answer locally.
#[tokio::test]
async fn scoped_reads_match_the_local_client() {
    use memvault_core::{DetailLevel, NodeKind, QueryScope};
    let (client, _own) = client_and_bucket().await;
    let bucket = fresh_bucket(&client, "parity").await;
    let other = fresh_bucket(&client, "parity-other").await;
    let local = memvault_web::ui::state::local_client().unwrap();
    let word = format!("parityword{}", std::process::id());
    let doc = put(&client, &format!("{word} doc"), &word, &bucket).await;
    let mut props = std::collections::BTreeMap::new();
    props.insert(
        "name".to_string(),
        serde_json::json!(format!("{word} entity")),
    );
    let ent = client
        .add_entity(
            Entity {
                id: memvault_core::EntityId::random(),
                kind: "person".into(),
                props,
                edges_out: vec![],
            },
            Visibility::Internal,
            Some(&bucket),
        )
        .await
        .unwrap();
    let gone = put(&client, "gone", &word, &bucket).await;
    client
        .retract_node(
            &format!("doc:{}", hex::encode(gone.0)),
            "retracted for parity",
        )
        .await
        .unwrap();

    let in_bucket = QueryScope::all().with_bucket(Some(bucket.clone()));
    for scope in [
        in_bucket.clone(),
        in_bucket.clone().with_kind(Some(NodeKind::Document)),
        in_bucket.clone().with_kind(Some(NodeKind::GraphEntity)),
        in_bucket.clone().with_detail(DetailLevel::Full),
    ] {
        let sorted = |mut v: Vec<memvault_api::NodeSummary>| {
            v.sort_by(|a, b| a.node_id.cmp(&b.node_id));
            serde_json::to_value(v).unwrap()
        };
        let want = sorted(local.list_scoped(&scope, 100).await.unwrap());
        let got = sorted(client.list_scoped(&scope, 100).await.unwrap());
        assert_eq!(got, want, "list_scoped {scope:?}");
        assert_eq!(
            client.count_scoped(&scope).await.unwrap(),
            local.count_scoped(&scope).await.unwrap(),
            "count_scoped {scope:?}"
        );
    }
    // Searches of every kind, in the bucket named.
    let mut hits = vec![];
    for _ in 0..50 {
        hits = client.search_scoped(&in_bucket, &word, 20).await.unwrap();
        if hits.len() >= 2 {
            break;
        }
        tokio::time::sleep(std::time::Duration::from_millis(100)).await;
    }
    let ids = |h: &[memvault_query::UnifiedHit]| {
        let mut v: Vec<String> = h.iter().map(|h| h.node_id.clone()).collect();
        v.sort();
        v
    };
    let want = local.search_scoped(&in_bucket, &word, 20).await.unwrap();
    assert_eq!(ids(&hits), ids(&want));
    assert!(hits.iter().any(|h| h.node_type == "entity"), "{hits:?}");
    let entities_only = in_bucket.clone().with_kind(Some(NodeKind::GraphEntity));
    let got = client
        .search_scoped(&entities_only, &word, 20)
        .await
        .unwrap();
    assert!(
        !got.is_empty() && got.iter().all(|h| h.node_type == "entity"),
        "{got:?}"
    );
    assert!(
        client
            .search_scoped(
                &QueryScope::all().with_bucket(Some(other.clone())),
                &word,
                20
            )
            .await
            .unwrap()
            .is_empty(),
        "another bucket's search finds nothing"
    );

    // By-id reads honour the scope's bucket.
    let elsewhere = QueryScope::all().with_bucket(Some(other.clone()));
    assert!(
        client
            .get_doc_scoped(&doc, &in_bucket)
            .await
            .unwrap()
            .is_some()
    );
    assert_eq!(
        client
            .get_doc_scoped(&doc, &elsewhere)
            .await
            .unwrap()
            .is_some(),
        local
            .get_doc_scoped(&doc, &elsewhere)
            .await
            .unwrap()
            .is_some(),
    );
    let label = format!("doc:{}", hex::encode(doc.0));
    assert_eq!(
        client
            .resolve_label_scoped(&label, &elsewhere)
            .await
            .unwrap(),
        local
            .resolve_label_scoped(&label, &elsewhere)
            .await
            .unwrap(),
    );
    assert_eq!(
        client
            .node_bucket(&NodeRef::Entity(ent.clone()))
            .await
            .unwrap(),
        Some(bucket.clone())
    );

    // Retracted rows stay hidden from a caller who may not see them, even
    // when asked for.
    let retracted = in_bucket
        .clone()
        .with_retraction(memvault_core::RetractionMode::IncludeRetracted);
    let rows = client.list_scoped(&retracted, 100).await.unwrap();
    assert!(!rows.iter().any(|r| r.retracted), "{rows:?}");
    let docs = client
        .list_docs_ex(None, 100, Some(&bucket), true)
        .await
        .unwrap();
    assert!(!docs.iter().any(|d| d.id == gone));
    let ents = client
        .list_entities_ex(100, Some(&bucket), false)
        .await
        .unwrap();
    assert!(ents.iter().any(|e| e.id == ent));
}

/// Responses follow standards/api-wire-conventions.md: bare arrays, node
/// labels in `node_id`, 201/204, hex ids and CID strings — never byte arrays.
#[tokio::test]
async fn responses_follow_the_wire_conventions() {
    let (client, own) = client_and_bucket().await;
    let own_hex = hex::encode(own.0);
    // The VFS part in a bucket of its own (tests share the agent bucket and
    // would race on its VFS root).
    let vfs_hex = hex::encode(fresh_bucket(&client, "wire-vfs").await.0);

    // Creates: 201 and the label in `node_id`.
    let resp = raw(reqwest::Method::POST, "/entities")
        .await
        .json(&serde_json::json!({ "kind": "note" }))
        .send()
        .await
        .unwrap();
    assert_eq!(resp.status(), 201);
    let ent = resp.json::<serde_json::Value>().await.unwrap()["node_id"]
        .as_str()
        .expect("node_id")
        .to_string();
    let resp = raw(reqwest::Method::POST, "/docs")
        .await
        .json(&serde_json::json!({ "body": "conventions" }))
        .send()
        .await
        .unwrap();
    assert_eq!(resp.status(), 201);
    let body: serde_json::Value = resp.json().await.unwrap();
    let doc = body["node_id"].as_str().expect("node_id").to_string();
    assert!(doc.starts_with("doc:"));
    let cid = body["cid"].as_str().unwrap();
    assert!(memvault_core::cid_bytes_from_string(cid).is_ok(), "{cid}");
    let resp = raw(reqwest::Method::POST, "/skills")
        .await
        .json(&serde_json::json!({ "name": "wire-skill" }))
        .send()
        .await
        .unwrap();
    assert_eq!(resp.status(), 201);
    assert!(resp.json::<serde_json::Value>().await.unwrap()["node_id"].is_string());
    let resp = raw(reqwest::Method::POST, "/vfs/mkdir")
        .await
        .json(&serde_json::json!({ "path": "/wire/dir", "bucket": vfs_hex }))
        .send()
        .await
        .unwrap();
    assert_eq!(resp.status(), 201);
    assert!(resp.json::<serde_json::Value>().await.unwrap()["node_id"].is_string());
    let resp = raw(reqwest::Method::POST, "/buckets")
        .await
        .json(&serde_json::json!({ "name": "wire-bucket" }))
        .send()
        .await
        .unwrap();
    assert_eq!(resp.status(), 201);
    assert!(resp.json::<serde_json::Value>().await.unwrap()["bucket_id"].is_string());

    // Lists: bare arrays.
    for path in [
        format!("/nodes?bucket={own_hex}"),
        format!("/tags/{ent}"),
        format!("/vfs?bucket={vfs_hex}&path=/wire"),
        format!("/vfs/find?bucket={vfs_hex}&target={ent}"),
        "/views/no-such-view/members".to_string(),
        "/buckets/merges".to_string(),
    ] {
        let (status, body) = get_json(&path).await;
        assert_eq!(status, 200, "GET {path}");
        assert!(body.is_array(), "GET {path}: {body}");
    }

    // Mutations without a body: 204.
    let resp = raw(reqwest::Method::PUT, &format!("/tags/{ent}"))
        .await
        .json(&serde_json::json!({ "tags": [["k", "v"]] }))
        .send()
        .await
        .unwrap();
    assert_eq!(resp.status(), 204, "PUT /tags");
    let resp = raw(reqwest::Method::DELETE, &format!("/tags/{ent}"))
        .await
        .json(&serde_json::json!({ "tags": [["k", "v"]] }))
        .send()
        .await
        .unwrap();
    assert_eq!(resp.status(), 204, "DELETE /tags");
    let resp = raw(reqwest::Method::POST, "/vfs/mv")
        .await
        .json(&serde_json::json!({ "from": "/wire/dir", "to": "/wire/moved", "bucket": vfs_hex }))
        .send()
        .await
        .unwrap();
    assert_eq!(resp.status(), 204, "POST /vfs/mv");
    let resp = raw(
        reqwest::Method::DELETE,
        &format!("/entities/{}", ent.trim_start_matches("entity:")),
    )
    .await
    .send()
    .await
    .unwrap();
    assert_eq!(resp.status(), 204, "DELETE /entities");

    // Errors carry the ApiError body.
    let resp = raw(reqwest::Method::GET, "/buckets/zz")
        .await
        .send()
        .await
        .unwrap();
    assert_eq!(resp.status(), 400);
    let body: serde_json::Value = resp.json().await.expect("an ApiError body");
    assert!(body.get("error").is_some(), "{body}");

    // A file node's manifest decodes (it was always null) with CID strings.
    let file = client
        .upload_file(
            b"node manifest",
            Some("nm.txt"),
            "text/plain",
            vec![],
            "internal",
            Some(&own),
        )
        .await
        .unwrap();
    let (status, body) = get_json(&format!("/nodes/file:{}", hex::encode(&file))).await;
    assert_eq!(status, 200);
    assert_eq!(body["manifest"]["filename"], "nm.txt", "{body}");
    assert_no_byte_arrays(&body, "GET /nodes/{file}");
    let (_, body) = get_json(&format!("/files/{}/manifest", hex::encode(&file))).await;
    assert_no_byte_arrays(&body, "GET /files/{cid}/manifest");

    // Grants: a tagged audience with string ids.
    client
        .bucket_grant(
            &own,
            memvault_auth::GrantAudience::Role(AgentRole::Auditor),
            vec![memvault_auth::Action::Read],
            600,
        )
        .await
        .expect("bucket_grant");
    let (_, body) = get_json(&format!("/buckets/{own_hex}/grants")).await;
    assert_no_byte_arrays(&body, "GET /buckets/{id}/grants");
    assert!(
        body.as_array()
            .unwrap()
            .iter()
            .any(|g| g["audience"]["kind"] == "role" && g["audience"]["role"] == "auditor"),
        "{body}"
    );
    let grants = client.bucket_grants_list(&own).await.unwrap();
    assert!(grants.iter().any(|g| matches!(
        g.audience,
        memvault_auth::GrantAudience::Role(AgentRole::Auditor)
    )));

    // Views carry a hex bucket id.
    let name = format!("bucketed-view-{}", std::process::id());
    client
        .create_view(memvault_api::View {
            name: name.clone(),
            tags: vec![],
            created_ns: 0,
            cid: String::new(),
            bucket_id: Some(own.clone()),
        })
        .await
        .unwrap();
    let (_, body) = get_json("/views").await;
    assert_no_byte_arrays(&body, "GET /views");

    // Traversal: the step shape the MCP tool emits too.
    let a = client
        .add_entity(entity("ta"), Visibility::Internal, Some(&own))
        .await
        .unwrap();
    let b = client
        .add_entity(entity("tb"), Visibility::Internal, Some(&own))
        .await
        .unwrap();
    client
        .add_link(
            &NodeRef::Entity(a.clone()),
            edge("to", NodeRef::Entity(b)),
            Visibility::Internal,
        )
        .await
        .unwrap();
    let (_, body) = get_json(&format!("/traverse?from=entity:{}", hex::encode(a.0))).await;
    let step = &body[0]["path"][0];
    assert!(
        step["edge_id"].is_string() && step["relation"] == "to",
        "{body}"
    );
}

#[tokio::test]
async fn share_lists_answer_over_http() {
    let (client, _own) = client_and_bucket().await;
    client.share_inbox().await.expect("share_inbox over HTTP");
    client.share_outbox().await.expect("share_outbox over HTTP");
}

#[tokio::test]
async fn events_carry_hex_bucket_ids_and_cid_strings() {
    let (client, _own) = client_and_bucket().await;
    let mut resp = raw(reqwest::Method::GET, "/events")
        .await
        .send()
        .await
        .unwrap();
    let mine = fresh_bucket(&client, "evented").await;
    let cid = memvault_core::cid_from_bytes(b"event").to_bytes();
    server()
        .await
        .event_bus
        .publish(memvault_api::MemvaultEvent::BucketCreated {
            bucket_id: mine.clone(),
            cid: cid.clone(),
        });
    let mut seen = String::new();
    let want = hex::encode(mine.0);
    while !seen.contains(&want) {
        let chunk = tokio::time::timeout(std::time::Duration::from_secs(10), resp.chunk())
            .await
            .expect("the bucket event arrives")
            .unwrap()
            .expect("stream open");
        seen.push_str(&String::from_utf8_lossy(&chunk));
    }
    assert!(
        seen.contains(&memvault_core::cid_string_from_bytes(&cid).unwrap()),
        "{seen}"
    );
}
