//! End-to-end tests for the memvault HTTP surface the openclaw MCP uses.
//!
//! These boot a **real** axum server over TCP, backed by an enrolled-agent
//! `LocalClient`, and drive it through `HttpApiClient` — the exact transport
//! the `mcp-memvault` plugin runs with (`MEMVAULT_URL=http://127.0.0.1:8401`).
//! Each MCP tool is a thin wrapper over a `MemvaultClient` call (or a
//! `memvault_api::vfs::*` helper that composes several), so exercising those
//! here covers the tool surface faithfully — and would have caught the stubbed
//! `add_link`/`edges_of`/`add_entity` paths that made `vfs_mkdir` return
//! entity:000…000 with no resolvable path.

use std::collections::{HashMap, HashSet};
use std::sync::Arc;

use ed25519_dalek::{Signer, SigningKey};
use tokio::sync::{OnceCell, RwLock};

use memvault_api::agent_identity::{enroll_local_agent, AgentIdentity};
use memvault_api::{EventBus, HttpApiClient, LocalClient, MemvaultClient};
use memvault_auth::node_attestation::{AttestationOrigin, NodeAttestation};
use memvault_auth::{jwt::NodeTrust, AgentRole};
use memvault_core::{AgentName, BucketId, ClusterId, NodeRef, PeerId, Visibility};
use memvault_doc::Entity;
use memvault_query::QuotaManager;
use memvault_store::MemvaultStore;
use memvault_web::{build_router, AppState};

const AGENT_ID: &str = "test-agent";

struct TestServer {
    base_url: String,
    identity: Arc<AgentIdentity>,
}

static SERVER: OnceCell<TestServer> = OnceCell::const_new();

/// Boot the enrolled-agent server once for the whole test binary.
async fn server() -> &'static TestServer {
    SERVER
        .get_or_init(|| async {
            // reqwest (used by HttpApiClient) is built with rustls-no-provider;
            // install a process-wide crypto provider before any client is built.
            let _ = rustls::crypto::ring::default_provider().install_default();

            // Deterministic admin + node keys; the agent key is generated by
            // `enroll_local_agent` and lives in `identity_dir`.
            let admin = SigningKey::from_bytes(&[0xA7u8; 32]);
            let node = SigningKey::from_bytes(&[0xB7u8; 32]);
            let cluster_id = ClusterId([0x11u8; 32]);

            let dir = std::env::temp_dir().join(format!("mv-mcp-e2e-{}", std::process::id()));
            let _ = std::fs::remove_dir_all(&dir);
            std::fs::create_dir_all(&dir).unwrap();
            // ACL helpers (enforce_*/filter_readable) lazily open the global
            // client from MEMVAULT_DB unless one is injected; point it at this
            // temp store so nothing touches a real ~/.local/share db.
            unsafe {
                std::env::set_var("MEMVAULT_DATA_DIR", &dir);
                std::env::set_var("MEMVAULT_DB", dir.join("blocks.redb"));
            }

            let store = Arc::new(MemvaultStore::open(dir.join("blocks.redb")).unwrap());
            let client = Arc::new(LocalClient::new(
                store,
                Arc::new(RwLock::new(QuotaManager::new(Default::default()))),
                Arc::new(EventBus::new(64)),
                node.verifying_key().to_bytes().to_vec(),
                cluster_id.0.to_vec(),
            ));

            // Minimal genesis so the agent can be enrolled and ACL resolves.
            let genesis = memvault_auth::sign_admin_genesis(&admin, cluster_id.clone(), 1)
                .expect("sign_admin_genesis");
            client.set_admin_signing_key(admin.clone());
            client.set_pinned_admin_genesis(genesis);
            client.set_node_signing_key(node.clone());

            let identity = enroll_local_agent(
                &client,
                AGENT_ID,
                &dir.join("agent"),
                AgentRole::AgentHost,
                u64::MAX,
            )
            .expect("enroll_local_agent");
            let agent_pubkey = identity.verifying_key.to_bytes();

            // The ACL helpers consult the process-global client.
            memvault_web::ui::state::set_client(Arc::clone(&client));

            // Auth fixtures: admin-signed node attestation (node_trust) and an
            // agent-attestation lookup matching the enrolled agent.
            let mut node_att = NodeAttestation {
                cluster_id: cluster_id.clone(),
                member: PeerId(node.verifying_key().as_bytes().to_vec()),
                not_after_ns: u64::MAX,
                issued_via: AttestationOrigin::Direct,
                signature: [0u8; 64],
            };
            node_att.signature = admin.sign(&node_att.signing_bytes().unwrap()).to_bytes();
            let mut trust = HashMap::new();
            trust.insert(node.verifying_key().to_bytes(), NodeTrust::Attested(node_att));

            let agent_att = memvault_auth::sign_agent_attestation(
                &node,
                AgentName(AGENT_ID.to_string()),
                agent_pubkey,
                AgentRole::AgentHost,
                u64::MAX,
            )
            .expect("sign_agent_attestation");
            let lookup_att = agent_att.clone();

            let state = Arc::new(AppState {
                client: Arc::clone(&client) as Arc<dyn MemvaultClient>,
                event_bus: Arc::new(EventBus::new(16)),
                admin_pubkey: Some(admin.verifying_key()),
                node_trust: Arc::new(std::sync::RwLock::new(trust)),
                revoked_agents: Arc::new(std::sync::RwLock::new(HashSet::new())),
                revoked_nodes: Arc::new(std::sync::RwLock::new(HashSet::new())),
                metrics: Arc::new(memvault_api::metrics::Metrics::new()),
                agent_attestation_lookup: Some(Arc::new(move |pk: &[u8; 32]| {
                    (*pk == lookup_att.agent_pubkey).then(|| lookup_att.clone())
                })),
                allowed_origins: vec![],
            });

            let router = build_router(state);

            // Run the server on its OWN thread + runtime. `#[tokio::test]`
            // gives each test a fresh runtime that is torn down when the test
            // ends; a server spawned on the first test's runtime would die and
            // every later test would see "error sending request". A dedicated
            // thread keeps it alive for the whole test binary.
            let (tx, rx) = std::sync::mpsc::channel();
            std::thread::spawn(move || {
                let rt = tokio::runtime::Builder::new_current_thread()
                    .enable_all()
                    .build()
                    .unwrap();
                rt.block_on(async move {
                    let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
                    tx.send(listener.local_addr().unwrap()).unwrap();
                    let _ = axum::serve(listener, router).await;
                });
            });
            let addr = rx.recv().unwrap();

            TestServer {
                base_url: format!("http://{addr}"),
                identity: Arc::new(identity),
            }
        })
        .await
}

/// An authenticated HTTP client + the enrolled agent's own bucket.
async fn client_and_bucket() -> (HttpApiClient, BucketId) {
    let s = server().await;
    let client = HttpApiClient::new(&s.base_url, Some(Arc::clone(&s.identity))).unwrap();
    // The server derives the bucket from the JWT pubkey; the bytes here are
    // ignored over HTTP. Pass the real identity pubkey anyway.
    let bucket = client
        .ensure_agent_bucket(&s.identity.verifying_key.to_bytes(), AGENT_ID)
        .await
        .expect("ensure_agent_bucket");
    (client, bucket)
}

/// A dedicated bucket so VFS tests don't race on a shared root.
async fn fresh_bucket(client: &HttpApiClient, name: &str) -> BucketId {
    client
        .bucket_create(
            name,
            None,
            Visibility::Internal,
            memvault_core::classification::Classification::Internal,
            memvault_doc::BucketRole::Standard,
        )
        .await
        .expect("bucket_create")
}

const ZERO: [u8; 32] = [0u8; 32];

#[tokio::test]
async fn vfs_mkdir_resolve_ls_tree_round_trip() {
    let (client, _agent_bucket) = client_and_bucket().await;
    let bucket = fresh_bucket(&client, "vfs-mkdir-test").await;

    // mkdir -p /reports/2026 — the regression: this used to return
    // entity:000…000 and leave nothing resolvable.
    let id = client
        .vfs_mkdir(&bucket, "/reports/2026")
        .await
        .expect("mkdir");
    assert_ne!(id.0, ZERO, "mkdir must return a real (non-zero) entity id");

    // The leaf resolves.
    let resolved = client
        .vfs_resolve(&bucket, "/reports/2026")
        .await
        .expect("resolve_path");
    assert!(resolved.is_some(), "freshly created dir must resolve");

    // ls / shows reports.
    let entries = client
        .vfs_ls(&bucket, "/", false)
        .await
        .expect("ls");
    assert!(
        entries.iter().any(|e| e.name == "reports"),
        "ls / must list the new 'reports' dir, got {:?}",
        entries.iter().map(|e| &e.name).collect::<Vec<_>>()
    );

    // tree contains the nested path.
    let tree = client
        .vfs_tree(&bucket, "/", 10)
        .await
        .expect("tree");
    assert!(tree.contains("2026"), "tree must include the nested dir: {tree}");
}

#[tokio::test]
async fn graph_entity_and_edges_round_trip() {
    let (client, bucket) = client_and_bucket().await;

    let mut props = std::collections::BTreeMap::new();
    props.insert("name".to_string(), serde_json::json!("alice"));
    let parent = client
        .add_entity(
            Entity {
                id: memvault_core::EntityId::random(),
                kind: "person".to_string(),
                props: props.clone(),
                edges_out: vec![],
            },
            Visibility::Internal,
            Some(&bucket),
        )
        .await
        .expect("add_entity parent");
    assert_ne!(parent.0, ZERO, "add_entity must not return a zero id");

    // get_entity round-trips.
    let got = client.get_entity(&parent).await.expect("get_entity");
    assert_eq!(got.expect("entity present").kind, "person");

    let child = client
        .add_entity(
            Entity {
                id: memvault_core::EntityId::random(),
                kind: "person".to_string(),
                props,
                edges_out: vec![],
            },
            Visibility::Internal,
            Some(&bucket),
        )
        .await
        .expect("add_entity child");

    let parent_ref = NodeRef::Entity(parent);
    let child_ref = NodeRef::Entity(child);

    // add_link used to be a no-op returning a random id; now it persists.
    let edge = memvault_doc::Edge {
        id: memvault_core::EdgeId::random(),
        relation: "knows".to_string(),
        target: child_ref.clone(),
        weight: None,
        props: Default::default(),
        provenance: None,
    };
    client
        .add_link(&parent_ref, edge, Visibility::Internal)
        .await
        .expect("add_link");

    // edges_of used to discard the response; now it returns the edge.
    let edges = client.edges_of(&parent_ref).await.expect("edges_of");
    assert!(
        edges
            .iter()
            .any(|(src, e)| *src == parent_ref && e.relation == "knows" && e.target == child_ref),
        "edges_of must return the persisted 'knows' edge"
    );
}

#[tokio::test]
async fn buckets_list_and_get_decode() {
    let (client, bucket) = client_and_bucket().await;

    // bucket_list/get used to fail to decode (server omitted required fields
    // and emitted hex ids that BucketId can't deserialize).
    let list = client.bucket_list().await.expect("bucket_list");
    assert!(
        list.iter().any(|b| b.id == bucket),
        "bucket_list must contain the agent bucket"
    );

    let got = client.bucket_get(&bucket).await.expect("bucket_get");
    let got = got.expect("agent bucket present");
    assert_eq!(got.id, bucket);
    // The elaborate fields are present (role defaults to Agent for agent buckets).
    assert_eq!(got.role, memvault_doc::BucketRole::Agent);
}

#[tokio::test]
async fn docs_put_get_and_search() {
    let (client, bucket) = client_and_bucket().await;

    let mut fm = std::collections::BTreeMap::new();
    fm.insert("title".to_string(), serde_json::json!("Quarterly Report"));
    let doc = memvault_doc::Document {
        id: memvault_core::DocId([0u8; 32]), // ignored; server assigns the id
        frontmatter: fm,
        body: "the kangaroo metric improved this quarter".to_string(),
    };
    let cid = client
        .put_doc(doc.clone(), vec![], Visibility::Internal, Some(&bucket))
        .await
        .expect("put_doc");
    assert!(!cid.is_empty(), "put_doc returns a cid");

    // search used to discard the response; the hit carries the authoritative
    // DocId (distinct from the 36-byte block CID returned by put_doc).
    let hits = client.search("kangaroo", 10).await.expect("search");
    let doc_id = hits.first().expect("search must find the indexed doc").doc_id.clone();

    let got = client.get_doc(&doc_id).await.expect("get_doc");
    assert_eq!(
        got.expect("doc present").body,
        "the kangaroo metric improved this quarter"
    );

    // list_docs used to drop every row (server sent `doc:<hex>` labels, client
    // hand-parsed them as bare hex). It now decodes DocSummary directly.
    let docs = client
        .list_docs(None, 50, Some(&bucket))
        .await
        .expect("list_docs");
    assert!(
        docs.iter().any(|d| d.id == doc_id),
        "list_docs must return the doc it stored, got {} rows",
        docs.len()
    );
    // The summary's cid is the content address, round-trips as CID bytes.
    let summary = docs.iter().find(|d| d.id == doc_id).unwrap();
    assert!(!summary.cid.is_empty(), "DocSummary.cid must be populated");
}

#[tokio::test]
async fn views_crud_round_trip() {
    let (client, _bucket) = client_and_bucket().await;

    let view = memvault_api::View {
        name: "e2e-view".to_string(),
        tags: vec![("kind".to_string(), "note".to_string())],
        created_ns: 0,
        cid: String::new(),
        bucket_id: None,
    };
    client.create_view(view.clone()).await.expect("create_view");

    let views = client.list_views().await.expect("list_views");
    assert!(views.iter().any(|v| v.name == "e2e-view"), "view must be listed");

    let got = client.get_view("e2e-view").await.expect("get_view");
    assert!(got.is_some(), "get_view must return the created view");

    client.delete_view("e2e-view").await.expect("delete_view");
    let after = client.list_views().await.expect("list_views after delete");
    assert!(
        !after.iter().any(|v| v.name == "e2e-view"),
        "view must be gone after delete"
    );
}

#[tokio::test]
async fn vfs_link_unlink_round_trip() {
    let (client, _agent_bucket) = client_and_bucket().await;
    let bucket = fresh_bucket(&client, "vfs-link-test").await;

    // Create an entity (its 32-byte id is known exactly), link it at a VFS
    // path, confirm it resolves, then unlink.
    let entity = client
        .add_entity(
            Entity {
                id: memvault_core::EntityId::random(),
                kind: "note".to_string(),
                props: Default::default(),
                edges_out: vec![],
            },
            Visibility::Internal,
            Some(&bucket),
        )
        .await
        .expect("add_entity");
    let node_id = format!("entity:{}", hex::encode(entity.0));

    let target = memvault_core::NodeRef::from_tag_label(&node_id).expect("node ref");
    client
        .vfs_link(&bucket, "/notes/linked.md", &target)
        .await
        .expect("vfs_link");

    let resolved = client
        .vfs_resolve(&bucket, "/notes/linked.md")
        .await
        .expect("resolve_path");
    assert!(resolved.is_some(), "linked node must resolve at its path");

    client
        .vfs_unlink(&bucket, "/notes/linked.md")
        .await
        .expect("unlink_path");
    let after = client
        .vfs_resolve(&bucket, "/notes/linked.md")
        .await
        .expect("resolve_path after unlink");
    assert!(after.is_none(), "node must be gone after unlink");
}

#[tokio::test]
async fn tags_add_and_get() {
    let (client, bucket) = client_and_bucket().await;
    let entity = client
        .add_entity(
            Entity {
                id: memvault_core::EntityId::random(),
                kind: "thing".to_string(),
                props: Default::default(),
                edges_out: vec![],
            },
            Visibility::Internal,
            Some(&bucket),
        )
        .await
        .expect("add_entity");
    let node_id = format!("entity:{}", hex::encode(entity.0));

    client
        .add_tags(&node_id, vec![("color".to_string(), "blue".to_string())])
        .await
        .expect("add_tags");
    let tags = client.get_tags(&node_id).await.expect("get_tags");
    assert!(
        tags.iter().any(|(s, l)| s == "color" && l == "blue"),
        "get_tags must return the added tag"
    );
}

#[tokio::test]
async fn status_reports_node() {
    let (client, _bucket) = client_and_bucket().await;
    // status() backs the memvault_status MCP tool.
    let status = client.status().await.expect("status");
    // NodeStatus now decodes peer_id/cluster_id (the old hand-parse dropped
    // them — it returned empty vecs).
    assert!(!status.peer_id.is_empty(), "status must carry peer_id");
    assert!(!status.cluster_id.is_empty(), "status must carry cluster_id");
}

#[tokio::test]
async fn listing_and_vfs_are_bucket_scoped() {
    let (client, _agent) = client_and_bucket().await;
    let a = fresh_bucket(&client, "scope-a").await;
    let b = fresh_bucket(&client, "scope-b").await;

    // A doc in each bucket.
    let mk = |body: &str| memvault_doc::Document {
        id: memvault_core::DocId([0u8; 32]),
        frontmatter: Default::default(),
        body: body.to_string(),
    };
    client.put_doc(mk("alpha doc"), vec![], Visibility::Internal, Some(&a)).await.expect("put a");
    client.put_doc(mk("beta doc"), vec![], Visibility::Internal, Some(&b)).await.expect("put b");

    // list_docs must be bucket-scoped: the two buckets return disjoint,
    // non-empty doc sets. (The old HTTP client dropped the bucket param, so
    // every bucket returned the same all-buckets list.)
    let da = client.list_docs(None, 50, Some(&a)).await.expect("list a");
    let db = client.list_docs(None, 50, Some(&b)).await.expect("list b");
    let aids: std::collections::HashSet<_> = da.iter().map(|d| d.id.clone()).collect();
    let bids: std::collections::HashSet<_> = db.iter().map(|d| d.id.clone()).collect();
    assert!(!aids.is_empty() && !bids.is_empty(), "each bucket must list its own doc");
    assert!(aids.is_disjoint(&bids), "list_docs must be bucket-scoped, not global");

    // VFS in the non-default bucket B: mkdir → resolve → tree (the
    // customer-plan-ai symptom was resolve failing / tree empty here).
    client.vfs_mkdir(&b, "/scoped/dir").await.expect("mkdir b");
    assert!(
        client.vfs_resolve(&b, "/scoped/dir").await.expect("resolve b").is_some(),
        "VFS path must resolve in a non-default bucket"
    );
    let tree = client.vfs_tree(&b, "/", 10).await.expect("tree b");
    assert!(tree.contains("scoped"), "tree must show the dir in bucket B: {tree}");
    // list_entities is bucket-scoped: B's root entity must be visible.
    let ents_b = client.list_entities(50, Some(&b)).await.expect("list_entities b");
    assert!(!ents_b.is_empty(), "bucket B must surface its VFS entities");
}

#[tokio::test]
async fn traverse_from_returns_neighbours() {
    let (client, bucket) = client_and_bucket().await;
    let a = client
        .add_entity(
            Entity {
                id: memvault_core::EntityId::random(),
                kind: "n".to_string(),
                props: Default::default(),
                edges_out: vec![],
            },
            Visibility::Internal,
            Some(&bucket),
        )
        .await
        .expect("add a");
    let b = client
        .add_entity(
            Entity {
                id: memvault_core::EntityId::random(),
                kind: "n".to_string(),
                props: Default::default(),
                edges_out: vec![],
            },
            Visibility::Internal,
            Some(&bucket),
        )
        .await
        .expect("add b");
    let a_ref = NodeRef::Entity(a);
    let b_ref = NodeRef::Entity(b);
    client
        .add_link(
            &a_ref,
            memvault_doc::Edge {
                id: memvault_core::EdgeId::random(),
                relation: "rel".to_string(),
                target: b_ref.clone(),
                weight: None,
                props: Default::default(),
                provenance: None,
            },
            Visibility::Internal,
        )
        .await
        .expect("add_link");

    // traverse_from used to return empty (no /traverse route + client stub).
    let hits = client
        .traverse_from(&a_ref, None, 2)
        .await
        .expect("traverse_from");
    assert!(
        hits.iter().any(|h| h.node == b_ref),
        "traverse from A must reach B"
    );
}

#[tokio::test]
async fn pin_unpin_and_extracted_text() {
    let (client, bucket) = client_and_bucket().await;
    // Upload a small text file, then exercise pin/unpin/extracted-text — these
    // used to be no-op/empty stubs with no server routes at all.
    let cid = client
        .upload_file(
            b"hello pinned world",
            Some("note.txt"),
            "text/plain",
            vec![],
            "internal",
            Some(&bucket),
        )
        .await
        .expect("upload_file");
    client.pin_file(&cid).await.expect("pin_file");
    // list_pinned must succeed over HTTP (it used to be an empty stub). The
    // exact pin bookkeeping (manifest vs content cid) is LocalClient-internal,
    // so we only require the round-trip to work, not a specific membership.
    let _pinned = client.list_pinned().await.expect("list_pinned");
    client.unpin_file(&cid).await.expect("unpin_file");
    // extracted-text may be None for a plain upload; the call must succeed.
    client.read_extracted_text(&cid).await.expect("read_extracted_text");
}
