//! `MEMVAULT_UI_AUTH=jwt`: the web UI signs in with the agent JWT a proxy
//! sends in the Authorization header (its own process: the mode is global).

use std::collections::{HashMap, HashSet};
use std::sync::Arc;

use ed25519_dalek::{Signer, SigningKey};
use tokio::sync::{OnceCell, RwLock};

use memvault_api::agent_identity::{AgentIdentity, enroll_local_agent};
use memvault_api::{EventBus, HttpApiClient, LocalClient, MemvaultClient};
use memvault_auth::node_attestation::{AttestationOrigin, NodeAttestation};
use memvault_auth::{AgentRole, jwt::NodeTrust};
use memvault_core::{AgentName, ClusterId, PeerId};
use memvault_query::QuotaManager;
use memvault_store::MemvaultStore;
use memvault_web::{AppState, build_router};

const AGENT_ID: &str = "test-agent";

struct TestServer {
    base_url: String,
    identity: Arc<AgentIdentity>,
}

static SERVER: OnceCell<TestServer> = OnceCell::const_new();

/// Boot the enrolled-agent server once for the whole test binary.
async fn server() -> &'static TestServer {
    SERVER
        .get_or_init(|| async {
            // reqwest (used by HttpApiClient) is built with rustls-no-provider;
            // install a process-wide crypto provider before any client is built.
            let _ = rustls::crypto::ring::default_provider().install_default();

            // Deterministic admin + node keys; the agent key is generated by
            // `enroll_local_agent` and lives in `identity_dir`.
            let admin = SigningKey::from_bytes(&[0xA7u8; 32]);
            let node = SigningKey::from_bytes(&[0xB7u8; 32]);
            let cluster_id = ClusterId([0x11u8; 32]);

            let dir = std::env::temp_dir().join(format!("mv-ui-jwt-{}", std::process::id()));
            let _ = std::fs::remove_dir_all(&dir);
            std::fs::create_dir_all(&dir).unwrap();
            // ACL helpers (enforce_*/filter_readable) lazily open the global
            // client from MEMVAULT_DB unless one is injected; point it at this
            // temp store so nothing touches a real ~/.local/share db.
            unsafe {
                std::env::set_var("MEMVAULT_DATA_DIR", &dir);
                std::env::set_var("MEMVAULT_DB", dir.join("blocks.redb"));
            }

            let store = Arc::new(MemvaultStore::open(dir.join("blocks.redb")).unwrap());
            let client = Arc::new(LocalClient::new(
                store,
                Arc::new(RwLock::new(QuotaManager::new(Default::default()))),
                Arc::new(EventBus::new(64)),
                node.verifying_key().to_bytes().to_vec(),
                cluster_id.0.to_vec(),
            ));

            // Minimal genesis so the agent can be enrolled and ACL resolves.
            let genesis = memvault_auth::sign_admin_genesis(&admin, cluster_id.clone(), 1)
                .expect("sign_admin_genesis");
            client.set_admin_signing_key(admin.clone());
            client.set_pinned_admin_genesis(genesis);
            client.set_node_signing_key(node.clone());

            let identity = enroll_local_agent(
                &client,
                AGENT_ID,
                &dir.join("agent"),
                AgentRole::AgentHost,
                u64::MAX,
            )
            .expect("enroll_local_agent");
            let agent_pubkey = identity.verifying_key.to_bytes();

            // The ACL helpers consult the process-global client.
            memvault_web::ui::state::set_client(Arc::clone(&client));

            // Auth fixtures: admin-signed node attestation (node_trust) and an
            // agent-attestation lookup matching the enrolled agent.
            let mut node_att = NodeAttestation {
                cluster_id: cluster_id.clone(),
                member: PeerId(node.verifying_key().as_bytes().to_vec()),
                not_after_ns: u64::MAX,
                issued_via: AttestationOrigin::Direct,
                signature: [0u8; 64],
            };
            node_att.signature = admin.sign(&node_att.signing_bytes().unwrap()).to_bytes();
            let mut trust = HashMap::new();
            trust.insert(
                node.verifying_key().to_bytes(),
                NodeTrust::Attested(node_att),
            );

            let agent_att = memvault_auth::sign_agent_attestation(
                &node,
                AgentName(AGENT_ID.to_string()),
                agent_pubkey,
                AgentRole::AgentHost,
                u64::MAX,
            )
            .expect("sign_agent_attestation");
            let lookup_att = agent_att.clone();

            let state = Arc::new(AppState {
                client: Arc::clone(&client) as Arc<dyn MemvaultClient>,
                event_bus: Arc::new(EventBus::new(16)),
                admin_pubkey: Some(admin.verifying_key()),
                node_trust: Arc::new(std::sync::RwLock::new(trust)),
                revoked_agents: Arc::new(std::sync::RwLock::new(HashSet::new())),
                revoked_nodes: Arc::new(std::sync::RwLock::new(HashSet::new())),
                metrics: Arc::new(memvault_api::metrics::Metrics::new()),
                agent_attestation_lookup: Some(Arc::new(move |pk: &[u8; 32]| {
                    (*pk == lookup_att.agent_pubkey).then(|| lookup_att.clone())
                })),
                allowed_origins: vec![],
            });

            // The UI signs in with the JWT a proxy puts in front of it.
            memvault_web::ui::state::set_ui_auth(memvault_web::ui::state::UiAuth::Jwt);
            let router = build_router(state);

            // Run the server on its OWN thread + runtime. `#[tokio::test]`
            // gives each test a fresh runtime that is torn down when the test
            // ends; a server spawned on the first test's runtime would die and
            // every later test would see "error sending request". A dedicated
            // thread keeps it alive for the whole test binary.
            let (tx, rx) = std::sync::mpsc::channel();
            std::thread::spawn(move || {
                let rt = tokio::runtime::Builder::new_current_thread()
                    .enable_all()
                    .build()
                    .unwrap();
                rt.block_on(async move {
                    let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
                    tx.send(listener.local_addr().unwrap()).unwrap();
                    let _ = axum::serve(listener, router).await;
                });
            });
            let addr = rx.recv().unwrap();

            TestServer {
                base_url: format!("http://{addr}"),
                identity: Arc::new(identity),
            }
        })
        .await
}

#[tokio::test]
async fn the_ui_signs_in_with_the_proxys_jwt() {
    let s = server().await;
    let http = reqwest::Client::new();
    let url = format!("{}/api/v1/auth/session-token", s.base_url);
    let none = http.get(&url).send().await.unwrap();
    assert_eq!(none.status(), 401, "no proxy, no session");
    assert!(none.text().await.unwrap().contains("Authorization"));
    let bad = http
        .get(&url)
        .bearer_auth("not-a-jwt")
        .send()
        .await
        .unwrap();
    assert_eq!(bad.status(), 401);
    let jwt = s.identity.issue_jwt("read write", 300).unwrap();
    let ok = http.get(&url).bearer_auth(&jwt).send().await.unwrap();
    assert_eq!(ok.status(), 200);
    assert!(
        ok.headers()
            .get_all("set-cookie")
            .iter()
            .any(|c| c.to_str().unwrap().starts_with("memvault_session=")),
        "the session cookie"
    );
    let body: serde_json::Value = ok.json().await.unwrap();
    assert_eq!(
        (body["token"].as_str(), body["agent_id"].as_str()),
        (Some(jwt.as_str()), Some(AGENT_ID)),
        "{body}"
    );
}

#[tokio::test]
async fn a_client_with_someone_elses_token_acts_as_them() {
    let s = server().await;
    let jwt = s.identity.issue_jwt("read write", 300).unwrap();
    let c = HttpApiClient::with_token(&s.base_url, &jwt).unwrap();
    let hits = c.search("anything", 5).await;
    assert!(hits.is_ok(), "the agent may search: {hits:?}");
    let nobody = HttpApiClient::with_token(&s.base_url, "not-a-jwt").unwrap();
    assert!(
        nobody.search("anything", 5).await.is_err(),
        "the API refuses a bad token"
    );
}
